kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: leganck/simple-dns
      tags: latest
      auto_tag: true
      force_tag: true

trigger:
  event:
    - tag
    - push
